# Generated by Django 5.2 on 2025-05-27 19:53

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('periodo', models.CharField(help_text='Ej: 20-30 Min', max_length=100)),
                ('hora', models.TimeField(default=datetime.time(10, 0), help_text='Hora de inicio en que se ofrece el servicio')),
            ],
        ),
    ]
