# Generated by Django 5.2 on 2025-05-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='periodo',
        ),
        migrations.AddField(
            model_name='servicio',
            name='turnos',
            field=models.ManyToManyField(help_text='Selecciona en qué turnos se ofrece este servicio', related_name='servicios', to='servicios.turnohorario'),
        ),
    ]
