# Generated by Django 5.2 on 2025-04-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='periodo',
            field=models.CharField(default='17:00 a 20:00 hs', help_text='Ej: 17:00 a 18:00 hs', max_length=100),
            preserve_default=False,
        ),
    ]
