# Generated by Django 5.2 on 2025-06-08 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_turnohorario_remove_servicio_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnohorario',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AddField(
            model_name='turnohorario',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
