# Generated by Django 5.2 on 2025-06-08 04:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0002_remove_profesional_turnos'),
        ('servicios', '0003_turnohorario_hora_fin_turnohorario_hora_inicio'),
        ('turnos', '0005_alter_turno_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='turnos',
        ),
        migrations.DeleteModel(
            name='TurnoHorario',
        ),
        migrations.AddField(
            model_name='servicio',
            name='turnos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mañana', 'Turno Mañana'), ('tarde', 'Turno Tarde'), ('noche', 'Turno Noche')], default=['mañana', 'tarde', 'noche'], max_length=20),
        ),
    ]
