# Generated by Django 5.2 on 2025-06-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0004_remove_servicio_turnos_delete_turnohorario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la profesión')),
                ('servicios', models.ManyToManyField(blank=True, related_name='profesiones', to='servicios.servicio')),
            ],
        ),
    ]
