# Generated by Django 5.2 on 2025-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_perfil_genero_perfil_telefono_alter_perfil_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='profesion',
            field=models.CharField(blank=True, default='No tiene', help_text='Profesión del usuario si es profesional', max_length=50, null=True),
        ),
    ]
