# Generated by Django 5.2 on 2025-05-28 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0002_turnohorario_remove_servicio_hora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('TER', 'Terapeuta'), ('MAS', 'Masajista'), ('EST', 'Esteticista'), ('COS', 'Cosmetóloga'), ('MAN', 'Manicurista'), ('PED', 'Pedicurista'), ('DEP', 'Especialista en Depilación'), ('FAC', 'Facialista'), ('SPA', 'Especialista en Spa'), ('OTR', 'Otro')], max_length=3)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('servicios', models.ManyToManyField(blank=True, to='servicios.servicio')),
                ('turnos', models.ManyToManyField(blank=True, help_text='Selecciona en qué turnos trabaja este profesional', related_name='profesionales', to='servicios.turnohorario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
