# Generated by Django 5.2 on 2025-06-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='turnos',
        ),
    ]
