# Generated by Django 5.2 on 2025-06-11 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesion', '0001_initial'),
        ('profesional', '0002_remove_profesional_turnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='titulo',
        ),
        migrations.AddField(
            model_name='profesional',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesion.profesion'),
        ),
    ]
