# Generated by Django 5.2 on 2025-06-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesion', '0001_initial'),
        ('profesional', '0003_remove_profesional_titulo_profesional_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='profesion',
        ),
        migrations.AddField(
            model_name='profesional',
            name='profesiones',
            field=models.ManyToManyField(blank=True, to='profesion.profesion'),
        ),
    ]
