# Generated by Django 5.2 on 2025-06-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0004_remove_profesional_profesion_profesional_profesiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='servicios',
        ),
    ]
