# Generated by Django 5.2 on 2025-05-28 03:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_turnohorario_remove_servicio_hora_and_more'),
        ('turnos', '0002_turno_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='turno',
            name='turno',
            field=models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], default='manana', max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_turno', to='servicios.servicio'),
        ),
    ]
