# Generated by Django 5.2 on 2025-06-08 03:37

import apps.turnos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_turnohorario_hora_fin_turnohorario_hora_inicio'),
        ('turnos', '0003_remove_turno_cliente_nombre_remove_turno_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.turnohorario'),
        ),
    ]
