# Generated by Django 5.2 on 2025-06-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_turno_usuario_alter_turno_hora_alter_turno_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Turno Mañana'), ('tarde', 'Turno Tarde'), ('noche', 'Turno Noche')], max_length=10),
        ),
    ]
