# Generated by Django 5.2 on 2025-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_turno_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='turno',
            name='dni',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
