# Generated by Django 5.2 on 2025-06-10 03:20

import apps.reservas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0004_remove_servicio_turnos_delete_turnohorario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('mañana', 'Turno Mañana'), ('tarde', 'Turno Tarde'), ('noche', 'Turno Noche')], max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_reserva', to='servicios.servicio')),
                ('usuario', models.ForeignKey(default=apps.reservas.models.obtener_usuario_por_defecto, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
